"""empty message

Revision ID: 218de08a4ac9
Revises: 
Create Date: 2023-08-20 21:41:52.995190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '218de08a4ac9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deposite_history',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('account', sa.String(), nullable=False),
    sa.CheckConstraint('amount >= 0'),
    sa.ForeignKeyConstraint(['account'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deposite_history')
    # ### end Alembic commands ###
