"""empty message

Revision ID: 396b83d6da6c
Revises: c14daf811275
Create Date: 2023-09-11 12:27:48.818542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '396b83d6da6c'
down_revision = 'c14daf811275'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_account_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_account_type',
    sa.Column('id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('parent_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('user', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['account_type.id'], name='user_account_type_parent_id_fkey'),
    sa.ForeignKeyConstraint(['user'], ['user.id'], name='user_account_type_user_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_account_type_pkey')
    )
    # ### end Alembic commands ###
