"""empty message

Revision ID: c14daf811275
Revises: ede52f5c5c65
Create Date: 2023-09-03 14:11:49.846680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c14daf811275'
down_revision = 'ede52f5c5c65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_account_type',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('parent_id', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('user', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['account_type.id'], ),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_account_type')
    # ### end Alembic commands ###
