"""empty message

Revision ID: ede52f5c5c65
Revises: 218de08a4ac9
Create Date: 2023-08-26 22:03:33.259950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ede52f5c5c65'
down_revision = '218de08a4ac9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'deposite_history', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'deposite_history', type_='unique')
    # ### end Alembic commands ###
